title: Private
description: Private This
template:
  repo: private-template
  name: private
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First stepk
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
